name: soffritto_uptodate
channels:
  - defaults
  - pytorch
  - conda-forge
  - bioconda  # Added bioconda for pysam
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3 
  - pip
  - pysam  # Added pysam here to read BAM files. e.g. Alignments
  - pip:
      - torch