name: soffritto_uptodate
channels:
  - conda-forge
  - defaults
  - pytorch
  - bioconda

dependencies:
  - python=3.9
  - pip
  - numpy=1.19.4
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - pysam
